// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izsufscvndolkxvcloiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6c3Vmc2N2bmRvbGt4dmNsb2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTg1NzMsImV4cCI6MjA2NTU5NDU3M30.Tme6lkXA_W1tA1NmqFx5nRN9C1WxHjo5wL051_QcvZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);